### ISSUE TITLE
.NET6 Support

### ISSUE THREAD

**Issue by schhwork** [dotMorten/System.Device#1]
Any possiblity for this to be supporetd by .net6? Or is there some equivalent im unaware of. This is literally the last namespace i need to to be able to migrate to .net6.

Any help whatsoever would be appreciated.

**Comment by dotMorten** [comment]
Target `net6.0-windows10.0.19041.0`+ and you'll have access to the more modern GeoLocation APIs that are not using deprecated APIs.
This is also mentioned in the note [in the readme](https://github.com/dotMorten/System.Device#note)

**Comment by mysticetus** [comment]
Another option:

I forked dotMorton's repo a few months ago and made it compile under net6.0-windows, fixed and applied all the latest VS2022/latest C# suggestions, etc. Haven't tested all the functionality in System.Device, but our users now run 24x7 on win10 tablets with our winforms app reading the built-in GPS via this assembly. No complaints yet.

https://github.com/Entiat/System.Device

**Comment by dotMorten** [comment]
@mysticetus I don't get why you'd spend the time porting this library. Why use my library that literally exposes the exact same API as net6.0-windows will give you access to, but in that case use the proper underlying Windows 10 WinRT APIs exposed the correct way? There's literally no point in this repo for anyone on Windows 10 and targeting net6.0-windows10.0.xxxxx.

This repo only served as a stopgap until that became possible, and why you don't really see any maintenance for this going forward.

**Comment by mysticetus** [comment]
Because it was a lower risk way to solve the problem that didn't entail a line of code changed in the main app (which has a rather complex cascade of issues should anything tip over or we horkle our (slightly) complicated interaction with the gps)? One of these days we'll devote enough testing time to switch to the new apis. Until then, this works great.
